### ISSUE TITLE
CMAKE_JS_LIB variable not being populated

### ISSUE THREAD

**Issue by jamezmoran** [cmake-js/cmake-js#107]
In the general usage for cmake-js, it states to put the following line in the CMakeLists.txt:

    target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB})

However, printing this var out using message reveals that CMAKE_JS_LIB is empty, so this line is redundant. This is more problematic when an executable is trying to link to the node addon (for example, when making a test driver) because it's unable to find the definitions for napi functions. Is this intended?

**Comment by unbornchikken** [comment]
Intended. It's the "general" usage, because on Windows you gotta link to node.lib, but on Linux there is nothing to get linked to. So that's why `CMAKE_JS_LIB` could be empty on some platforms. But it is easier to use and document that way that you should put that line into you lists on all platforms instead of you should write a sophisticated platform aware lists for your simple node module.

**Comment by Julusian** [comment]
It is intended that `CMAKE_JS_LIB` is empty except on windows.
I'm struggling to understand how this problem is manifesting for you, as this is clearly working fine for most users.

Do you have an example project or log to share that will help reproduce this? 
I am also tempted to close this as it sounds a bit stale with no responses in 4 years

**Comment by deionut** [comment]
I have the same issue when compiling with cmake-js on Mac OS; both CMAKE_JS_SRC and CMAKE_JS_LIB are empty.
If "is intended that CMAKE_JS_LIB is empty except on windows" how do I link on platforms other than Windows?

I am actually trying to build an executable (I use Google test to test one node.js module). The google test is an executable, and if I do add_executable the build fails at linking undefined V8 methods but if I do add_library it builds but of course the non-executable google test won't run. Here is my CMakeLists.txt:

make_minimum_required(VERSION 3.14)

include_directories(my_project)

set(CMAKE_CXX_STANDARD 14)

set(CMAKE_C_FLAGS "-Wno-pointer-sign -fno-signed-char -std=c99 -fpermissive")

set(CMAKE_CXX_FLAGS "-Wno-pointer-sign -fno-signed-char -std=c99 -fpermissive")

project (addon)

include(FetchContent)

FetchContent_Declare(

  googletest

  GIT_REPOSITORY https://github.com/google/googletest.git

  GIT_TAG release-1.12.1

)

FetchContent_MakeAvailable(googletest)

include_directories(${CMAKE_JS_INC} "my_project/include/pkcs11/v2.40/")

file(GLOB SOURCE_FILES "my_project/*.c" "my_project/*.h" "my_project/*.cpp")

add_library(${PROJECT_NAME} SHARED ${SOURCE_FILES} ${CMAKE_JS_SRC})

set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")

target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB} )

## google_test

enable_testing()

file(GLOB TEST_FILES "test/*.cc" "test/utils/*.c")

add_executable(

  my_project_google_test

  ${TEST_FILES}

)

target_include_directories(my_project_google_test

PRIVATE

test/utils/*.h

)

target_link_libraries(

  my_project_google_test

  PRIVATE

  GTest::gtest_main

  ${CMAKE_JS_LIB}

)

include(GoogleTest)

gtest_discover_tests(my_project_google_test)

**Comment by Julusian** [comment]
I think the issue here is that you are trying to using `add_executable` instead of `add_library` as you want an executable. 

For typical node addon building, we don't need to link against a node binary (except on windows), and instead rely on the knowledge that the v8 (or whatever) symbols will be available at runtime, which 'satisfies' the linking errors you are seeing.
But when building an executable, the missing symbols means that your executable will not be able to run, so the compiler rightfully fails.

I think that trying to satisfy the linking is going to be quite complex. While it might be possible to link against a prebuilt node executable, trying to actually run the result will probably fail as the nodejs environment wont be setup, so the calls to any methods there will be undefined behaviour or will fail.  
I dont think this is something under the scope of this tool, the focus here is for building node addons.

My suggestion to solve this is to either do your nodes in js (jest/mocha) or split your c/c++ code so that there is a non-node c/c++ library which googletest should then be happy with, with a second library which wraps that into a node module.

**Comment by deionut** [comment]
Thanks a lot!
