### ISSUE TITLE
Verify SHASUMS256.txt gpg signature

### ISSUE THREAD

**Issue by gjasny** [cmake-js/cmake-js#111]
Hello,

right now cmake-js does not verify the signature of the `SHASUMS256.txt` file. If anyone manages to poison the local DNS resolver, untrusted NodeJS binaries might be executed.

cmake-js should check the gpg signature of the `SHASUMS256.txt` and also compare the fingerprint of the signing key against an embedded whitelist.

Additionally https should be used to downloads.

Thanks,
Gregor

**Comment by unbornchikken** [comment]
The SHA sum lies right next to binaries on the same server, so if anyone hijacks the DNS, SHA sum files will be manipulated also along with the binaries for sure. There is no easy way arount this.

Regarding expected whitelist. Idea of CMake.js was a build tool that offers same features like node-gyp has. Since node-gyp doesn't have sophisticated, white list based security features integrated, CMake.js doesn't have it either. I don't want to spend time and effort for managing a whitelist in a project that "binaries" are plain text files.

However it would be better if CMake.js use https instead of http, so I file this thread as a bug to fix that.

**Comment by unbornchikken** [comment]
https used as of 3.6.2
