### ISSUE TITLE
prebuilt binaries downloads as a feature .

### ISSUE THREAD

**Issue by zuohuadong** [cmake-js/cmake-js#206]
https://github.com/grpc/grpc-node/issues/1274

Grpc:
Until cmake.js gets prebuilt binaries downloads as a feature, we won't consider switching to it.

**Comment by unbornchikken** [comment]
Yeah, that would be really nice to have for sure. (Un:))Fortunately I have too many little kids atm, so a PR would be greatly appreciated.

**Comment by Kreijstal** [comment]
This would be amazing, really, maybe use the github release feature, to just download the thing

**Comment by Julusian** [comment]
why not just use [prebuild](https://www.npmjs.com/package/prebuild) and [prebuild-install](https://www.npmjs.com/package/prebuild-install) in your projects? They work perfectly well with cmake-js (using it [here](https://github.com/julusian/node-jpeg-turbo)) and avoid the need to reinvent something that is already very widely used

**Comment by aminya** [comment]
@Julusian `prebuild` doesn't have first-class cmake-js support. The development for prebuild is very slow when it comes to merging the pull requests related to cmake-js. 

https://github.com/prebuild/prebuild/pull/254
https://github.com/prebuild/prebuildify/pull/7

I think we can make a cmake-js version of prebuildify to fix all the issues.

**Comment by Julusian** [comment]
Ah ok. Ive not encountered any issues that werent easily fixable, and nothing has broken on me since starting to use it.

> prebuild/prebuild#254

This is just for their unit tests, so while something that should have been merged, it does not affect real usage in any way

> prebuild/prebuild#269

That looks to me like a cmake misconfiguration rather than something wrong with prebuild

> prebuild/prebuild-install#138

If anything I want to argue that those cmake-js config fields don't make any sense to me for a library, as surely you want to support any combination of the values you can provide? But its such a minor quality of life change that will only help those who are configuring a new project

> prebuild/prebuildify#49
> prebuild/prebuildify#7

These two are reasonable. I did briefly think about switching something to prebuildify, but couldnt because of lack of cmake-js support, so a new prebuildify would be reasonable.

But I would strongly urge against trying to replace prebuild-install. Mainly because electron bundlers need to know how to rebuild dependencies for the target platform. From what I have seen in a couple of them, they are aware that node-pre-gyp and prebuild-install are tools which should be invoked, and so will manually do so with the correct platform, arch and runtime flags set. 
So a new cmake specific tool will need to be known by them for any libraries using the cmake prebuild tool to be easily usable in electron apps. That will take time even if you dont have to convince someone it is worth supporting. I submitted a fix there in late January to fix napi prebuilds, and it hasnt yet been published all the way through the dependency tree.  
I suspect this will not be the case for a prebuildify solution.

**Comment by aminya** [comment]
We have been building a new all-in-one solution that fixes the issues of the current ecosystems, but it is still not stable. It supports cross-prebuilding for other operating systems and runtimes!
https://github.com/EmbeddedEnterprises/cmake-ts

**Comment by Julusian** [comment]
For anyone who finds this, I did not have any issues prebuild&prebuild-install with cmake-js, other than prebuild forcing an older version of cmake-js, but you can fix this with yarn resolutions or equivalent.

I have since been playing around with [my own alternative to prebuildify and node-gyp-build](https://www.npmjs.com/package/pkg-prebuilds). It is rather opinionated, but I have it in use in 3 libraries now for a few months with the only issue reported was because I am not prebuilding for nwjs. In fact I moved one of them accross from node-gyp-build recently, because node-gyp-build was choosing the wrong binary and this was an easy fix.  
I did consider making it part of this project, but decided it was better to have separate as it doesnt care if cmake-js or node-gyp is being used.
