### ISSUE TITLE
"cmake-js configure" auto add generator "Visual Studio 15 2017 Win64'"

### ISSUE THREAD

**Issue by chengsu** [cmake-js/cmake-js#211]
I'm using cmake-js in wsl of win10，everytime I run `cmake-js configure`, it auto add generator `Visual Studio 15 2017 Win64`, and command fail，output like this:
```
[ '/home/chengjiabin/.nvm/versions/node/v10.16.3/bin/node',
  '/home/chengjiabin/.nvm/versions/node/v10.16.3/bin/cmake-js',
  'configure',
  '-G',
  'Visual Studio 15 2017 Win64' ]
```
I'm wondering how to remove the default generator.

**Comment by Julusian** [comment]
Im not certain on this, but I am pretty sure that cmake-js can't be adding those parameters there, unless you invoked some other command. (Otherwise cmake-js will get itself into an infinite loop)

As this is quite an old issue, Im going to close it, but if it is still a problem then do reply with more details (version of cmake-js, ideally a example project) and this can be reopened
