### ISSUE TITLE
How to skip auto detecting of VS?

### ISSUE THREAD

**Issue by eduardtudor21** [cmake-js/cmake-js#223]
I have an isolated copy of VS C++ tooling which of course CMake can find perfectly. Auto detecting seems redundant if CMake already do this.

**Comment by Julusian** [comment]
From what I can tell, we arent telling cmake where to find the tooling, but we are telling it what version to use. This is necessary because if we don't then it defaults to 'NMake Makefiles' which will almost never work.
cmake-js could definitely do better at finding VS. Does node-gyp find it? I am thinking of reusing some of their logic for finding vs

**Comment by Julusian** [comment]
I have been digging into this today. As I suspected, we need to tell cmake what version of visual studio it needs to use, so we do need to locate visual studio ourselves.
I have borrowed some logic from node-gyp which uses a modern method of locating visual studio, unlike the method we were doing before. Additionally, we now respect the `msvs_version` config field that node-gyp does.

This will be included in the upcoming 7.0.0 release
