### ISSUE TITLE
win_delay_load_hook is broken when using on electron with napi

### ISSUE THREAD

**Issue by warmist** [cmake-js/cmake-js#291]
Hi,
I'm not experienced with this js/node/electron infrastructure but after few days of debugging it seems that delay load is broken.

It used to work like this:

- first check if you are trying to find "node.exe"
- return your own process handle

Now it checks for "node.dll" which in electron workflow is never loaded.

Commit that broke it: c99e10eb08a519119e2fff30212857e073b81f61
For comparison this is the correct delay load hook: [node-gyp](https://github.com/nodejs/node-gyp/blob/e2401e1395bef1d3c8acec268b42dc5fb71c4a38/src/win_delay_load_hook.cc)

**Comment by Julusian** [comment]
Do you have something I could use to reproduce this? My attempts to try and reproduce this have been unsuccessul. I tried with an electron exe, building with pkg, and copying and renaming a node.exe.

I changed the delay load hook so that it would work with nw.js, as the old one was not compatible for them.

There was a PR opened here #289 that I hope will fix this. published in v7.1.0
