### ISSUE TITLE
Electron not auto detected and runtime fail

### ISSUE THREAD

**Issue by Bilb** [cmake-js/cmake-js#303]
Hey, I am using cmake-js 7.2.1 and I have a question about https://github.com/cmake-js/cmake-js#important
It means that I need to install cmake-js as part of my electron application, and not as part of my node_module.
But to compile my node_module I need to tell cmake-js where to look which I do with 
`yarn cmake-js compile --directory node_modules/my_node_module --log-level silly`

However, doing so, cmake-js does not realize it should build for electron as printed in this message
```bash
info TOOL Using Unix Makefiles generator.
info CMD CONFIGURE
info RUN [
info RUN   'cmake',
info RUN   '[...]/node_modules/my_node_module',
info RUN   '--no-warn-unused-cli',
info RUN   '-G',
info RUN   'Unix Makefiles',
info RUN   '-DCMAKE_JS_VERSION=7.2.1',
info RUN   '-DCMAKE_BUILD_TYPE=Release',
info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/[...]/node_modules/my_node_module/build/Release',
info RUN   '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>',
info RUN   '-DCMAKE_JS_INC=/home/user/.cmake-js/node-x64/v16.13.0/include/node;/home/user/pro/contribs/electron_app/node_modules/my_node_module/node_modules/nan',
info RUN   '-DCMAKE_JS_SRC=',
info RUN   '-DNODE_RUNTIME=node',
info RUN   '-DNODE_RUNTIMEVERSION=16.13.0',
info RUN   '-DNODE_ARCH=x64',
info RUN   '-DCMAKE_JS_LIB=',
info RUN   '-DCMAKE_CXX_FLAGS=-DBUILDING_NODE_EXTENSION'
info RUN ]
```

So, instead I've tried forcing it with the cmake-js in package.json as this: 
```json
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "17.4.10", // this is the version I have in my yarn.lock
    "arch": "x64"
  },
```

It builds fine, but when I start the electron app. The node process crashes I think, and I just a dead app with dead dev tools.
The crash happens on the first call to the native module.
In the terminal I just get "Error sending from webFrameMain:  {}""

Would you be able to help me understand what is going on?

Thanks

**Comment by Julusian** [comment]
It might work to use `@electron/rebuild` to rebuild your library to the correct version of electron, I am unsure if that tool handles cmake-js correctly (I have never used it myself)

If it is a build issue, then my recommendation is to port the library to be node-api based instead of nan. That will mean it wouldn't need to be compiled for any specific version of node or electron, node-api is designed to be api compatible across versions (except for when electron broke one method a few releases back). Of course this may not be possible for technical or time reasons.

If it is crashing when first using your library, then it should either be doing so with the standard module incompatibility message, or it sounds like a bug in the c++ code, causing a segfault or something. It is hard to suggest anything more seeing as it didn't really log anything useful.  
Perhaps you could try using it with electron running in nodejs mode https://www.electronjs.org/docs/latest/api/environment-variables#electron_run_as_node, maybe this will cause the crash  or log output to be more useful? It will probably require writing a test script to get the library to do things without using anything electron.

**Comment by Bilb** [comment]
can confirm it was fixed after moving to node-api
