### ISSUE TITLE
Choosing non-top VS generator (feature request)

### ISSUE THREAD

**Issue by pergy** [cmake-js/cmake-js#32]
Hello,

As far as I see, when `cmake-js` initializes the `Toolset` on Windows, we just grab the top version of Visual Studio as generator. Somewhere [here](https://github.com/cmake-js/cmake-js/blob/master/lib/es6/toolset.js#L167)
I could use an option which defines the generator explicitly, like in CMake:
``` cmake build . -G "Visual Studio 12 2013" ```
Any chance for that?

Thanks

**Comment by unbornchikken** [comment]
There can be an option for choosing generator of course. The main idea behind CMake.js is that it should just work. You can have the benefit of choosing specific generators during module development, but once your module's users start to install it on their systems, the build should be automatic. That's why I haven't put too mutch effort for supporting cmake build process specializations.

**Comment by pergy** [comment]
I see.
Anyway, it can be a problem for those who using 3rdparty library in their node module. Versions should be match in that case.

**Comment by unbornchikken** [comment]
Yup, but what would be a purpose of a module that cannot be deployed to computers those not have a specific version of a compiler of a specific platform?

**Comment by unbornchikken** [comment]
Anyway, I'm planning to add support for proxying arguments and npm config values from CMake.js to CMake, that would satify your needs there.

**Comment by pergy** [comment]
Thanks! ;)
