### ISSUE TITLE
cmake build tools

### ISSUE THREAD

**Issue by madCoder24** [cmake-js/cmake-js#46]
I have installed the build tools and when I run 'cmake-js build'. The command fails saying there is no Visual C++ compiler installed. Am I missing something? Does there need to be an environment variable setup?

**Comment by unbornchikken** [comment]
No, it should work as is. I've tested it on a plain install of Windows 7 and 8.1. Did you install [it](https://www.microsoft.com/en-us/download/details.aspx?id=49983) for sure? Because there is [another build tool](https://www.microsoft.com/en-us/download/details.aspx?id=48159) that is for .NET only.

**Comment by madCoder24** [comment]
Yes that is what I installed, I even went as far as uninstalling everything involving C++ and installing Visual Studio community edition. During the install, I selected Visual C++ to be installed and still nothing was found. I am running Windows 10. Does that matter?

**Comment by unbornchikken** [comment]
I'm behind a W10/VSC2015 right now, and everything works as expected. It looks like a CMake issue to me: https://cmake.org/Bug/view.php?id=15831 However I cannot reproduce this. Would you try it with CMake 3.3?

**Comment by madCoder24** [comment]
I installed CMake version 3.5.1 and it started working. That is what I get for using CLion and forgetting I don't actually have CMake installed. 

I appreciate the assistance.
