### ISSUE TITLE
OpenSSL linking?

### ISSUE THREAD

**Issue by lyssdod** [cmake-js/cmake-js#60]
Hi all,

Is this possible to use `cmake-js` to make an addon that required to use OpenSSL? `node-gyp` advises to do it like this: https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL

**Comment by unbornchikken** [comment]
Since CMake.js is just plain old CMake, any ossl vs cmake tutorial will do. Unfortunately I have no exprerience with it.
On Sep 17, 2016 14:14, Alex R <notifications@github.com> wrote:Hi all,

Is this possible to use cmake-js to make an addon that required to use OpenSSL? node-gyp advises to do it like this: https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL
