### ISSUE TITLE
Distributing cmake options in npm packages

### ISSUE THREAD

**Issue by jjrv** [cmake-js/cmake-js#66]
I'm maintaining the [`nbind`](https://github.com/charto/nbind#readme) project which autogenerates NAN and Emscripten bindings (and TypeScript definitions) for C++ classes and functions. It makes writing Node.js addons extremely easy but requires a number of compiler options to use especially when targeting Emscripten, so it comes with a couple of `.gypi` files.

Another tool, [`autogypi`](https://github.com/charto/autogypi#readme) autogenerates a `binding.gyp` file for a new project given names of packages it depends on. It plays nicely with both `nbind` and `nan`, noticing the former depends on the latter and sets everything up.

I'd like to add support for `cmake-js` in `nbind` and `autogypi`, so that these [quick start](https://github.com/charto/nbind#quick-start) instructions would be equally easy when using `cmake-js` instead of `node-gyp` (this would be an option). That would also get rid of the Python 2 dependency (unless targeting Emscripten, which still depends on it).

For this, maybe some sort of interaction between `cmake-js` and `autogypi` would be useful? Do you have any thoughts for a standard way to include the necessary `CMakeLists` options in npm packages intended to be used as C++ libraries?

**Comment by jjrv** [comment]
Also check out how `autogypi` finds `nan`:

```JavaScript
import * as Promise from 'bluebird';
import * as resolve from 'resolve';

Promise.promisify(resolve)(
	dep, // A string, such as "nan".
	{
		basedir: basePath, // Root of the package that wants to find nan.
		packageFilter: (json: any) => {
			json.main = 'package.json';
			return(json);
		}
	}
).then((entry: string) => { /* entry is the path to package.json in nan root */ }
```

As long as the package that wants to find `nan` lists it as a dependency in its `package.json`, this should find it on both `npm` versions 2 and 3. It's not specific to `nan`, it'll add the root of any package to the include path unless there's a `autogypi.json` file in the root with custom instructions. I guess it could be changed to also support a custom block inside `package.json`.

In any case, I'd like `cmake-js` (or `autogypi`) to similarly find other packages besides `nan` and read additional compiler options or whatever else needs to go into `CMakeLists`.

**Comment by unbornchikken** [comment]
That's how my [boost-lib](https://github.com/cmake-js/boost-lib) module works, it's a simple CMake include https://github.com/cmake-js/boost-lib#1-include. Of course it's not that fool proof, because it requires that boost-lib gotta get installed in the root node_modules folder. It's given with npm 3+ in almost 99.99% of cases. But if it's not, you can go with [find_path](https://cmake.org/cmake/help/v3.0/command/find_path.html), which will locate boost-lib in the depth of node_modules folders for sure. So the idea in CMake.js is that CMake is already a powerful build tool, we just don't need to invent its features in Node.

About you question at node-ffi. Please note that I'm working on an ffi module, that will fix the main issue of node-ffi, which is the performance. Or the lack of performance. You gotta pay with 100x+ overhead for its features and that's just not worth it. That's why I started my own module [fastcall](https://github.com/cmake-js/fastcall). With it you'll get almost the same performance (1.5-2x overhead at maximum) that you can have with yer shinny hand written C++ code but [with 100% JavaScript](https://github.com/cmake-js/fastcall/blob/master/test/suites/refTypes.js#L595). And fastcall is CMake based of course.

**Comment by jjrv** [comment]
I see, that's really nice! So if some new app (not using C++ at all) depends on npm package `foo`, and `foo` then depends on `boost-lib`... Should `foo` use `find_path` in its `CMakeLists`? Is that more efficient than if `cmake-js` had a way for `foo` to announce its dependency so it could use known Node.js logic to find `boost-lib`?

**Comment by unbornchikken** [comment]
There could be many solutions for this problem. CMake.js uses JS code to find nan, because that was by hand on that time when I made that part of that code. Boost lib uses cmake, because I wanted to test if that could be a viable solution or doesn't.

Right now I believe the best solution would be:

* boost-lib index.js: 
```js
//...
exports.path =__dirname
```

* foo module's CMakeLists.txt:
```cmake
EXEC_PROGRAM(node ${CMAKE_CURRENT_SOURCE_DIR}
		ARGS -p -e "require('boost-lib').path"
		OUTPUT_VARIABLE boostLibDirPath)
SET(CMAKE_MODULE_PATH  boostLibDirPath)
include(BoostLib)
```

I'm planning to improve both nan and boost-lib location strategies in the future.

**Comment by ed-alertedh** [comment]
Did anything ever come of this? I'm currently trying to port an existing lib built with CMake and being able to use the build files almost as-is would be amazing...

**Comment by Julusian** [comment]
It sounds like this was answered, and as nbind appears abandoned I dont see anything here that needs doing
